config/routes.rb
Depot::Application.routes.draw do
  resources :orders

  resources :line_items

  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, on: :member
  end

  root to: 'store#index', as: 'store'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
    price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  # GET /line_items
  # GET /line_items.json
  def index
    # @line_items = LineItem.all

    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @line_items }
    # end

      logger.error "Blocked access to line_items list via browser"
      redirect_to store_url, notice: 'Invalid path'
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    begin
      # @line_item = LineItem.find(params[:id])
    # rescue ActiveRecord::RecordNotFound
    #   logger.error "Attempt to access via browser line_item #{params[:id]}"
    #   redirect_to store_url, notice: 'line_item'
    # else
      #made line_item unavailable via broser
      # respond_to do |format|
      #  format.html # show.html.erb
      #   format.json { render json: @cart }
      # end  

      logger.error "Blocked access to line_items list via browser"
      redirect_to store_url, notice: 'Invalid path'

    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  # # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @cart = current_cart
    reset_visit
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)
    logger.error "what the hell #{@cart.inspect}"

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_path }
        format.js { @current_item = @line_item }
        format.json { render json: @line_item, status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def update
      @cart = current_cart
      to_add = Integer(params[:to_add])
      product = Product.find(params[:product_id])
      @removed = false;

      if( to_add > 0 )
        @cart.add_product(product.id, to_add)
      elsif( to_add == 0 )
        logger.error "Unexpected quantity to add"
      else
        @removed = @cart.remove_product(product.id, -to_add)
      end

      respond_to do |format|
        format.html { redirect_to store_path, notice: "changed quantity of #{params[:pr_title]}" }
        @removed ? format.js : format.js{ @current_item = LineItem.find(params[:id]) }
        format.json { head :ok }
      end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @cart = @line_item.cart

    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access via browser line_item #{params[:id]}"
      redirect_to store_url, notice: 'not found item to destroy'
    else
      @line_item.destroy
      logger.info 'destoy of the line item'

      respond_to do |format|
        format.html { redirect_to store_path, notice: "removed product #{params[:pr_title]} from the cart"}
        format.js
        format.json { head :ok }
      end
    end
  end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
  <tr id='current_item'>
<% else %>
  <tr>
<% end %>

  <td><%= line_item.quantity %>&times;</td>
  <td><%= line_item.product.title %></td>
  <td class='item_price'><%= number_to_currency(line_item.total_price) %></td>

<!--  <%= @remote_x_button = line_item.cart.products_quantity != 1 %> -->
<!--  <%= @remote_dash_button = line_item.cart.total_quantity != 1 %> -->

  <td><%= button_to 'x', line_item, method: :delete, remote: @remote_x_button %></td>
  <td><%= button_to '-', 
    { controller: 'line_items', action: 'update', id: line_item.id, to_add: -1, product_id: line_item.product.id }, 
    method: :put, 
    remote: @remote_dash_button %>
  </td>
  <td><%= button_to '+', 
    { controller: 'line_items', action: 'update', id: line_item.id, to_add: 1, product_id: line_item.product.id }, 
    method: :put, 
    remote:true %>
  </td>
</tr>

app/views/line_items/create.js.erb
$("#notice").hide();
if ($('#cart tr').length == 2) { $('#cart').show('blind', 1000); }
  
$('#cart').html("<%=j render @cart %>");
  
$('#current_item').css({'background-color':'#88ff88'}).
   animate({'background-color':'#114411'}, 1000);

app/views/line_items/destroy.js.erb
$('#cart').html("<%=j render @cart %>");

if ($('#cart tr').length == 2) { $('#cart').hide('blind', 1000); }

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <tr>
    <th>Product</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.product_id %></td>
    <td><%= link_to 'Show', line_item %></td>
    <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
    <td><%= link_to 'Destroy', line_item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @line_item.product_id %>
</p>


<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/update.js.erb
$('#cart').html("<%=j render @cart %>");

if ($('#cart tr').length == 2) { $('#cart').hide('blind', 1000); }

$('#current_item').css({'background-color':'#88ff88'}).
   animate({'background-color':'#114411'}, 1000);